databases:
  - name: finance_db
    databaseName: Finance_db
    user: postgres
    password: sohail
    plan: free

services:
  - type: web
    name: finance-tracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: gunicorn your_project_name.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: finance_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4